### ISSUE TITLE
HLL VIP stacktraces with "discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: ValueError: time data"

### ISSUE THREAD

**Issue by tunacado** [tunacado/fishbot#6]
**Describe the bug**
Error when performing `/hll vip`.

```
Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/root/fishbot/fishbot/cogs/hell_let_loose.py", line 127, in vip
    expiration = datetime.strptime(vip['vip_expiration'], "%Y-%m-%dT%H:%M:%S%z")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2222-12-29T06:01:08.144Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/root/fishbot/fishbot/cogs/hell_let_loose.py", line 442, in on_application_command_error
    raise error
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 1312, in _invoke
    await command.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: ValueError: time data '2222-12-29T06:01:08.144Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**To Reproduce**
1. Go to discord
2. Do `/hll vip` after your `steam64ID is registered`.
3. Observe error.

**Expected behavior**
Should return VIP time.

**Comment by tunacado** [comment]
Note this also happened with `/hll claim`:

```
Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 978, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/root/fishbot/fishbot/cogs/hell_let_loose.py", line 184, in claim
    expiration = datetime.strptime(vip['vip_expiration'], "%Y-%m-%dT%H:%M:%S%z") + timedelta(hours=grant_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2222-12-29T06:01:06.620Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/root/fishbot/fishbot/cogs/hell_let_loose.py", line 442, in on_application_command_error
    raise error
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 1312, in _invoke
    await command.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/root/.cache/pypoetry/virtualenvs/fishbot-mxrBL9zA-py3.11/lib/python3.11/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: ValueError: time data '2222-12-29T06:01:06.620Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by tunacado** [comment]
Should be fixed by https://github.com/tunacado/fishbot/commit/79073efafaa5618a95db827e00e9b2d7819a30ca, testing

**Comment by tunacado** [comment]
Tested working this morning, good to go.
